
package com.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LogisticslistingServiceDelegate", targetNamespace = "http://service.service.com/")
public interface LogisticslistingServiceDelegate {

	/**
	 * 
	 * @param llist
	 */
	@WebMethod
	@RequestWrapper(localName = "saveLlist", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveLlist")
	@ResponseWrapper(localName = "saveLlistResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveLlistResponse")
	public void saveLlist(@WebParam(name = "Llist", targetNamespace = "") Logisticslisting llist);

	/**
	 * 
	 * @param llists
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveBatch", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveBatch")
	@ResponseWrapper(localName = "saveBatchResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveBatchResponse")
	public String saveBatch(@WebParam(name = "Llists", targetNamespace = "") List<Logisticslisting> llists);

	/**
	 * 
	 * @param llist
	 */
	@WebMethod
	@RequestWrapper(localName = "deleteLlist", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteLlist")
	@ResponseWrapper(localName = "deleteLlistResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteLlistResponse")
	public void deleteLlist(@WebParam(name = "Llist", targetNamespace = "") Logisticslisting llist);

	/**
	 * 
	 * @return returns java.util.List<com.service.service.Logisticslisting>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllLlist", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllLlist")
	@ResponseWrapper(localName = "findAllLlistResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllLlistResponse")
	public List<Logisticslisting> findAllLlist();

	/**
	 * 
	 * @param params
	 * @return returns java.util.List<com.service.service.Logisticslisting>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findLlistByParams", targetNamespace = "http://service.service.com/", className = "com.service.service.FindLlistByParams")
	@ResponseWrapper(localName = "findLlistByParamsResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindLlistByParamsResponse")
	public List<Logisticslisting> findLlistByParams(
			@WebParam(name = "params", targetNamespace = "") List<String> params);

	/**
	 * 
	 * @param pkId
	 * @return returns com.service.service.Logisticslisting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findLlistByPkId", targetNamespace = "http://service.service.com/", className = "com.service.service.FindLlistByPkId")
	@ResponseWrapper(localName = "findLlistByPkIdResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindLlistByPkIdResponse")
	public Logisticslisting findLlistByPkId(@WebParam(name = "pkId", targetNamespace = "") String pkId);

	/**
	 * 
	 * @param param
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateLlistBySql", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateLlistBySql")
	@ResponseWrapper(localName = "updateLlistBySqlResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateLlistBySqlResponse")
	public String updateLlistBySql(@WebParam(name = "param", targetNamespace = "") String param);

	/**
	 * 
	 * @param userid
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findMaxImportnum", targetNamespace = "http://service.service.com/", className = "com.service.service.FindMaxImportnum")
	@ResponseWrapper(localName = "findMaxImportnumResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindMaxImportnumResponse")
	public String findMaxImportnum(@WebParam(name = "userid", targetNamespace = "") String userid);

	/**
	 * 
	 * @param llists
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateBatch", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateBatch")
	@ResponseWrapper(localName = "updateBatchResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateBatchResponse")
	public String updateBatch(@WebParam(name = "Llists", targetNamespace = "") List<Logisticslisting> llists);

	/**
	 * 
	 * @param pkids
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteBatch", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteBatch")
	@ResponseWrapper(localName = "deleteBatchResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteBatchResponse")
	public String deleteBatch(@WebParam(name = "pkids", targetNamespace = "") List<String> pkids);

	/**
	 * 
	 * @param param
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getYTOOddUpdateLog", targetNamespace = "http://service.service.com/", className = "com.service.service.GetYTOOddUpdateLog")
	@ResponseWrapper(localName = "getYTOOddUpdateLogResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.GetYTOOddUpdateLogResponse")
	public String getYTOOddUpdateLog(@WebParam(name = "param", targetNamespace = "") List<String> param);

}
