
package com.service.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* OddnumberServiceService service = new OddnumberServiceService();
* OddnumberServiceDelegate portType = service.getOddnumberServicePort();
* portType.deleteOddnum(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "OddnumberServiceService", targetNamespace = "http://service.service.com/", wsdlLocation = "http://47.91.140.252:7001/RPSService/OddnumberServicePort?wsdl")
public class OddnumberServiceService extends Service {

	private final static URL ODDNUMBERSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.service.service.OddnumberServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.service.OddnumberServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://47.91.140.252:7001/RPSService/OddnumberServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://47.91.140.252:7001/RPSService/OddnumberServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ODDNUMBERSERVICESERVICE_WSDL_LOCATION = url;
	}

	public OddnumberServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OddnumberServiceService() {
		super(ODDNUMBERSERVICESERVICE_WSDL_LOCATION,
				new QName("http://service.service.com/", "OddnumberServiceService"));
	}

	/**
	 * 
	 * @return returns OddnumberServiceDelegate
	 */
	@WebEndpoint(name = "OddnumberServicePort")
	public OddnumberServiceDelegate getOddnumberServicePort() {
		return super.getPort(new QName("http://service.service.com/", "OddnumberServicePort"),
				OddnumberServiceDelegate.class);
	}

}
