
package com.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OddnumerDiyServiceDelegate", targetNamespace = "http://service.service.com/")
public interface OddnumerDiyServiceDelegate {

	/**
	 * 
	 * @param type
	 * @param userid
	 * @return returns com.service.service.OddnumerDiy
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUseOddnumerDiy", targetNamespace = "http://service.service.com/", className = "com.service.service.GetUseOddnumerDiy")
	@ResponseWrapper(localName = "getUseOddnumerDiyResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.GetUseOddnumerDiyResponse")
	public OddnumerDiy getUseOddnumerDiy(@WebParam(name = "userid", targetNamespace = "") String userid,
			@WebParam(name = "type", targetNamespace = "") String type);

	/**
	 * 
	 * @param userid
	 * @return returns java.util.List<com.service.service.OddnumerDiy>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllOddnumDiyByUserid", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllOddnumDiyByUserid")
	@ResponseWrapper(localName = "findAllOddnumDiyByUseridResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllOddnumDiyByUseridResponse")
	public List<OddnumerDiy> findAllOddnumDiyByUserid(@WebParam(name = "userid", targetNamespace = "") String userid);

	/**
	 * 
	 * @param oddnum
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateOddnumDiy", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateOddnumDiy")
	@ResponseWrapper(localName = "updateOddnumDiyResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateOddnumDiyResponse")
	public String updateOddnumDiy(@WebParam(name = "Oddnum", targetNamespace = "") OddnumerDiy oddnum);

}
