
package com.service.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* OddnumerDiyServiceService service = new OddnumerDiyServiceService();
* OddnumerDiyServiceDelegate portType = service.getOddnumerDiyServicePort();
* portType.getUseOddnumerDiy(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "OddnumerDiyServiceService", targetNamespace = "http://service.service.com/", wsdlLocation = "http://47.91.140.252:7001/RPSService/OddnumerDiyServicePort?wsdl")
public class OddnumerDiyServiceService extends Service {

	private final static URL ODDNUMERDIYSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.service.service.OddnumerDiyServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.service.OddnumerDiyServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://47.91.140.252:7001/RPSService/OddnumerDiyServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://47.91.140.252:7001/RPSService/OddnumerDiyServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ODDNUMERDIYSERVICESERVICE_WSDL_LOCATION = url;
	}

	public OddnumerDiyServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OddnumerDiyServiceService() {
		super(ODDNUMERDIYSERVICESERVICE_WSDL_LOCATION,
				new QName("http://service.service.com/", "OddnumerDiyServiceService"));
	}

	/**
	 * 
	 * @return returns OddnumerDiyServiceDelegate
	 */
	@WebEndpoint(name = "OddnumerDiyServicePort")
	public OddnumerDiyServiceDelegate getOddnumerDiyServicePort() {
		return super.getPort(new QName("http://service.service.com/", "OddnumerDiyServicePort"),
				OddnumerDiyServiceDelegate.class);
	}

}
