
package com.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OddnumberServiceDelegate", targetNamespace = "http://service.service.com/")
public interface OddnumberServiceDelegate {

	/**
	 * 
	 * @param oddnum
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteOddnum", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteOddnum")
	@ResponseWrapper(localName = "deleteOddnumResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteOddnumResponse")
	public String deleteOddnum(@WebParam(name = "Oddnum", targetNamespace = "") Oddnumber oddnum);

	/**
	 * 
	 * @param oddnum
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateOddnum", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateOddnum")
	@ResponseWrapper(localName = "updateOddnumResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateOddnumResponse")
	public String updateOddnum(@WebParam(name = "Oddnum", targetNamespace = "") Oddnumber oddnum);

	/**
	 * 
	 * @param userid
	 * @return returns com.service.service.Oddnumber
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUseOddnumber", targetNamespace = "http://service.service.com/", className = "com.service.service.GetUseOddnumber")
	@ResponseWrapper(localName = "getUseOddnumberResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.GetUseOddnumberResponse")
	public Oddnumber getUseOddnumber(@WebParam(name = "userid", targetNamespace = "") String userid);

	/**
	 * 
	 * @param userid
	 * @return returns java.util.List<com.service.service.Oddnumber>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllOddnumByUserid", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllOddnumByUserid")
	@ResponseWrapper(localName = "findAllOddnumByUseridResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllOddnumByUseridResponse")
	public List<Oddnumber> findAllOddnumByUserid(@WebParam(name = "userid", targetNamespace = "") String userid);

	/**
	 * 
	 * @param oddnum
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveOddnum", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveOddnum")
	@ResponseWrapper(localName = "saveOddnumResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveOddnumResponse")
	public String saveOddnum(@WebParam(name = "Oddnum", targetNamespace = "") Oddnumber oddnum);

	/**
	 * 
	 * @param pkId
	 * @return returns com.service.service.Oddnumber
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findOddnumByPkId", targetNamespace = "http://service.service.com/", className = "com.service.service.FindOddnumByPkId")
	@ResponseWrapper(localName = "findOddnumByPkIdResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindOddnumByPkIdResponse")
	public Oddnumber findOddnumByPkId(@WebParam(name = "pkId", targetNamespace = "") String pkId);

}
