
package com.service.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* SysparamServiceService service = new SysparamServiceService();
* SysparamServiceDelegate portType = service.getSysparamServicePort();
* portType.findSysParamByPkId(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "SysparamServiceService", targetNamespace = "http://service.service.com/", wsdlLocation = "http://47.91.140.252:7001/RPSService/SysparamServicePort?wsdl")
public class SysparamServiceService extends Service {

	private final static URL SYSPARAMSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.service.service.SysparamServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.service.SysparamServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://47.91.140.252:7001/RPSService/SysparamServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://47.91.140.252:7001/RPSService/SysparamServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SYSPARAMSERVICESERVICE_WSDL_LOCATION = url;
	}

	public SysparamServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SysparamServiceService() {
		super(SYSPARAMSERVICESERVICE_WSDL_LOCATION, new QName("http://service.service.com/", "SysparamServiceService"));
	}

	/**
	 * 
	 * @return returns SysparamServiceDelegate
	 */
	@WebEndpoint(name = "SysparamServicePort")
	public SysparamServiceDelegate getSysparamServicePort() {
		return super.getPort(new QName("http://service.service.com/", "SysparamServicePort"),
				SysparamServiceDelegate.class);
	}

}
