
package com.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SysparamServiceDelegate", targetNamespace = "http://service.service.com/")
public interface SysparamServiceDelegate {

	/**
	 * 
	 * @param pkId
	 * @return returns com.service.service.Sysparam
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findSysParamByPkId", targetNamespace = "http://service.service.com/", className = "com.service.service.FindSysParamByPkId")
	@ResponseWrapper(localName = "findSysParamByPkIdResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindSysParamByPkIdResponse")
	public Sysparam findSysParamByPkId(@WebParam(name = "pkId", targetNamespace = "") String pkId);

	/**
	 * 
	 * @param sys
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateSysParam", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateSysParam")
	@ResponseWrapper(localName = "updateSysParamResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateSysParamResponse")
	public String updateSysParam(@WebParam(name = "sys", targetNamespace = "") Sysparam sys);

	/**
	 * 
	 * @return returns java.util.List<com.service.service.Sysparam>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllSysParam", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllSysParam")
	@ResponseWrapper(localName = "findAllSysParamResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllSysParamResponse")
	public List<Sysparam> findAllSysParam();

	/**
	 * 
	 * @param sys
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveSysParam", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveSysParam")
	@ResponseWrapper(localName = "saveSysParamResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveSysParamResponse")
	public String saveSysParam(@WebParam(name = "sys", targetNamespace = "") Sysparam sys);

	/**
	 * 
	 * @param sys
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteSysParam", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteSysParam")
	@ResponseWrapper(localName = "deleteSysParamResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteSysParamResponse")
	public String deleteSysParam(@WebParam(name = "sys", targetNamespace = "") Sysparam sys);

	/**
	 * 
	 * @param paramname
	 * @return returns com.service.service.Sysparam
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findSysByParamname", targetNamespace = "http://service.service.com/", className = "com.service.service.FindSysByParamname")
	@ResponseWrapper(localName = "findSysByParamnameResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindSysByParamnameResponse")
	public Sysparam findSysByParamname(@WebParam(name = "paramname", targetNamespace = "") String paramname);

}
