
package com.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserinfoServiceDelegate", targetNamespace = "http://service.service.com/")
public interface UserinfoServiceDelegate {

	/**
	 * 
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveUser", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveUser")
	@ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.SaveUserResponse")
	public String saveUser(@WebParam(name = "user", targetNamespace = "") Userinfo user);

	/**
	 * 
	 * @param user
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteUser", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteUser")
	@ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.DeleteUserResponse")
	public String deleteUser(@WebParam(name = "user", targetNamespace = "") Userinfo user);

	/**
	 * 
	 * @return returns java.util.List<com.service.service.Userinfo>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllUser", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllUser")
	@ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllUserResponse")
	public List<Userinfo> findAllUser();

	/**
	 * 
	 * @param userid
	 * @return returns com.service.service.Userinfo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findUserByUserId", targetNamespace = "http://service.service.com/", className = "com.service.service.FindUserByUserId")
	@ResponseWrapper(localName = "findUserByUserIdResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindUserByUserIdResponse")
	public Userinfo findUserByUserId(@WebParam(name = "userid", targetNamespace = "") String userid);

	/**
	 * 
	 * @param user
	 */
	@WebMethod
	@RequestWrapper(localName = "updateUser", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateUser")
	@ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdateUserResponse")
	public void updateUser(@WebParam(name = "user", targetNamespace = "") Userinfo user);

	/**
	 * 
	 * @param user
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "userLogin", targetNamespace = "http://service.service.com/", className = "com.service.service.UserLogin")
	@ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UserLoginResponse")
	public boolean userLogin(@WebParam(name = "user", targetNamespace = "") Userinfo user);

}
