
package com.service.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* UserinfoServiceService service = new UserinfoServiceService();
* UserinfoServiceDelegate portType = service.getUserinfoServicePort();
* portType.findUserByUserId(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "UserinfoServiceService", targetNamespace = "http://service.service.com/", wsdlLocation = "http://47.91.140.252:7001/RPSService/UserinfoServicePort?wsdl")
public class UserinfoServiceService extends Service {

	private final static URL USERINFOSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.service.service.UserinfoServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.service.UserinfoServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://47.91.140.252:7001/RPSService/UserinfoServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://47.91.140.252:7001/RPSService/UserinfoServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERINFOSERVICESERVICE_WSDL_LOCATION = url;
	}

	public UserinfoServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserinfoServiceService() {
		super(USERINFOSERVICESERVICE_WSDL_LOCATION, new QName("http://service.service.com/", "UserinfoServiceService"));
	}

	/**
	 * 
	 * @return returns UserinfoServiceDelegate
	 */
	@WebEndpoint(name = "UserinfoServicePort")
	public UserinfoServiceDelegate getUserinfoServicePort() {
		return super.getPort(new QName("http://service.service.com/", "UserinfoServicePort"),
				UserinfoServiceDelegate.class);
	}

}
