
package com.service.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "XysbhparamServiceDelegate", targetNamespace = "http://service.service.com/")
public interface XysbhparamServiceDelegate {

	/**
	 * 
	 * @param xysbh
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "savexysbh", targetNamespace = "http://service.service.com/", className = "com.service.service.Savexysbh")
	@ResponseWrapper(localName = "savexysbhResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.SavexysbhResponse")
	public String savexysbh(@WebParam(name = "xysbh", targetNamespace = "") Xysbhparam xysbh);

	/**
	 * 
	 * @param xysbh
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deletexysbh", targetNamespace = "http://service.service.com/", className = "com.service.service.Deletexysbh")
	@ResponseWrapper(localName = "deletexysbhResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.DeletexysbhResponse")
	public String deletexysbh(@WebParam(name = "xysbh", targetNamespace = "") Xysbhparam xysbh);

	/**
	 * 
	 * @param paramname
	 * @return returns com.service.service.Xysbhparam
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findXysbhByParamname", targetNamespace = "http://service.service.com/", className = "com.service.service.FindXysbhByParamname")
	@ResponseWrapper(localName = "findXysbhByParamnameResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindXysbhByParamnameResponse")
	public Xysbhparam findXysbhByParamname(@WebParam(name = "paramname", targetNamespace = "") String paramname);

	/**
	 * 
	 * @return returns java.util.List<com.service.service.Xysbhparam>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllXysbh", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllXysbh")
	@ResponseWrapper(localName = "findAllXysbhResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindAllXysbhResponse")
	public List<Xysbhparam> findAllXysbh();

	/**
	 * 
	 * @param pkId
	 * @return returns com.service.service.Xysbhparam
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findxysbhByPkId", targetNamespace = "http://service.service.com/", className = "com.service.service.FindxysbhByPkId")
	@ResponseWrapper(localName = "findxysbhByPkIdResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.FindxysbhByPkIdResponse")
	public Xysbhparam findxysbhByPkId(@WebParam(name = "pkId", targetNamespace = "") String pkId);

	/**
	 * 
	 * @param xysbh
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updatexysbh", targetNamespace = "http://service.service.com/", className = "com.service.service.Updatexysbh")
	@ResponseWrapper(localName = "updatexysbhResponse", targetNamespace = "http://service.service.com/", className = "com.service.service.UpdatexysbhResponse")
	public String updatexysbh(@WebParam(name = "xysbh", targetNamespace = "") Xysbhparam xysbh);

}
