
package com.service.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* UserinfoServiceImplService service = new UserinfoServiceImplService();
* UserinfoServiceImplDelegate portType = service.getUserinfoServiceImplPort();
* portType.main(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "UserinfoServiceImplService", targetNamespace = "http://impl.service.service.com/", wsdlLocation = "http://47.91.140.252:7001/RPSService/UserinfoServiceImplPort?wsdl")
public class UserinfoServiceImplService extends Service {

	private final static URL USERINFOSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.service.service.impl.UserinfoServiceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.service.impl.UserinfoServiceImplService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/RPSService/UserinfoServiceImplPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:8080/RPSService/UserinfoServiceImplPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERINFOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public UserinfoServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserinfoServiceImplService() {
		super(USERINFOSERVICEIMPLSERVICE_WSDL_LOCATION,
				new QName("http://impl.service.service.com/", "UserinfoServiceImplService"));
	}

	/**
	 * 
	 * @return returns UserinfoServiceImplDelegate
	 */
	@WebEndpoint(name = "UserinfoServiceImplPort")
	public UserinfoServiceImpl getUserinfoServiceImplPort() {
		return super.getPort(new QName("http://impl.service.service.com/", "UserinfoServiceImplPort"),
				UserinfoServiceImpl.class);
	}

}
