
package com.service.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserinfoServiceImpl", targetNamespace = "http://impl.service.service.com/")
public interface UserinfoServiceImpl {

	/**
	 * 
	 * @param args
	 */
	@WebMethod
	@RequestWrapper(localName = "main", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.Main")
	@ResponseWrapper(localName = "mainResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.MainResponse")
	public void main(@WebParam(name = "args", targetNamespace = "") List<String> args);

	/**
	 * 
	 * @param name
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getValue", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.GetValue")
	@ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.GetValueResponse")
	public String getValue(@WebParam(name = "name", targetNamespace = "") String name);

	/**
	 * 
	 * @param user
	 */
	@WebMethod
	@RequestWrapper(localName = "updateUser", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.UpdateUser")
	@ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.UpdateUserResponse")
	public void updateUser(@WebParam(name = "user", targetNamespace = "") Userinfo user);

	/**
	 * 
	 * @param user
	 */
	@WebMethod
	@RequestWrapper(localName = "deleteUser", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.DeleteUser")
	@ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.DeleteUserResponse")
	public void deleteUser(@WebParam(name = "user", targetNamespace = "") Userinfo user);

	/**
	 * 
	 * @param user
	 */
	@WebMethod
	@RequestWrapper(localName = "saveUser", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.SaveUser")
	@ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.SaveUserResponse")
	public void saveUser(@WebParam(name = "user", targetNamespace = "") Userinfo user);

	/**
	 * 
	 * @param userId
	 * @return returns com.service.service.impl.Userinfo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findUserByUserId", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindUserByUserId")
	@ResponseWrapper(localName = "findUserByUserIdResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindUserByUserIdResponse")
	public Userinfo findUserByUserId(@WebParam(name = "UserId", targetNamespace = "") String userId);

	/**
	 * 
	 * @return returns java.util.List<com.service.service.impl.Userinfo>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllUser", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindAllUser")
	@ResponseWrapper(localName = "findAllUserResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindAllUserResponse")
	public List<Userinfo> findAllUser();

}
