
package com.service.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LogisticslistingServiceImpl", targetNamespace = "http://impl.service.service.com/")
public interface LogisticslistingServiceImpl {

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<com.service.service.impl.Logisticslisting>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findLlistByParams", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindLlistByParams")
	@ResponseWrapper(localName = "findLlistByParamsResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindLlistByParamsResponse")
	public List<Logisticslisting> findLlistByParams(@WebParam(name = "arg0", targetNamespace = "") List<String> arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateLlist", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.UpdateLlist")
	@ResponseWrapper(localName = "updateLlistResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.UpdateLlistResponse")
	public void updateLlist(@WebParam(name = "arg0", targetNamespace = "") Logisticslisting arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateLlistBySql", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.UpdateLlistBySql")
	@ResponseWrapper(localName = "updateLlistBySqlResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.UpdateLlistBySqlResponse")
	public String updateLlistBySql(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findMaxImportnum", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindMaxImportnum")
	@ResponseWrapper(localName = "findMaxImportnumResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindMaxImportnumResponse")
	public String findMaxImportnum(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "deleteLlist", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.DeleteLlist")
	@ResponseWrapper(localName = "deleteLlistResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.DeleteLlistResponse")
	public void deleteLlist(@WebParam(name = "arg0", targetNamespace = "") Logisticslisting arg0);

	/**
	 * 
	 * @return returns java.util.List<com.service.service.impl.Logisticslisting>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllLlist", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindAllLlist")
	@ResponseWrapper(localName = "findAllLlistResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindAllLlistResponse")
	public List<Logisticslisting> findAllLlist();

	/**
	 * 
	 * @param arg0
	 * @return returns com.service.service.impl.Logisticslisting
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findLlistByPkId", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindLlistByPkId")
	@ResponseWrapper(localName = "findLlistByPkIdResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.FindLlistByPkIdResponse")
	public Logisticslisting findLlistByPkId(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "saveLlist", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.SaveLlist")
	@ResponseWrapper(localName = "saveLlistResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.SaveLlistResponse")
	public void saveLlist(@WebParam(name = "arg0", targetNamespace = "") Logisticslisting arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveBatch", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.SaveBatch")
	@ResponseWrapper(localName = "saveBatchResponse", targetNamespace = "http://impl.service.service.com/", className = "com.service.service.impl.SaveBatchResponse")
	public String saveBatch(@WebParam(name = "arg0", targetNamespace = "") List<Logisticslisting> arg0);

}
