
package com.service.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* OddnumberServiceImplService service = new OddnumberServiceImplService();
* OddnumberServiceImpl portType = service.getOddnumberServiceImplPort();
* portType.deleteOddnum(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "OddnumberServiceImplService", targetNamespace = "http://impl.service.service.com/", wsdlLocation = "http://47.91.140.252:7001/RPSService/OddnumberServiceImplPort?wsdl")
public class OddnumberServiceImplService extends Service {

	private final static URL ODDNUMBERSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.service.service.impl.OddnumberServiceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.service.impl.OddnumberServiceImplService.class.getResource(".");
			url = new URL(baseUrl, "http://47.91.140.252:7001/RPSService/OddnumberServiceImplPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://47.91.140.252:7001/RPSService/OddnumberServiceImplPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ODDNUMBERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public OddnumberServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OddnumberServiceImplService() {
		super(ODDNUMBERSERVICEIMPLSERVICE_WSDL_LOCATION,
				new QName("http://impl.service.service.com/", "OddnumberServiceImplService"));
	}

	/**
	 * 
	 * @return returns OddnumberServiceImpl
	 */
	@WebEndpoint(name = "OddnumberServiceImplPort")
	public OddnumberServiceImpl getOddnumberServiceImplPort() {
		return super.getPort(new QName("http://impl.service.service.com/", "OddnumberServiceImplPort"),
				OddnumberServiceImpl.class);
	}

}
